sudo: required
language: cpp
dist: trusty

before_install:
- svn co https://github.com/OpenMS/dockerfiles/trunk/travis
- docker build -t openms/qt5 -f travis/Dockerfile-qt5-travis .

script:
- docker run -e
  TRAVIS_REPO_SLUG -e
  TRAVIS_BRANCH -e
  TRAVIS_PULL_REQUEST -e
  TRAVIS_COMMIT_RANGE -e
  TRAVIS_COMMIT -e
  CXX -e
  "ENABLE_CLASS_TESTING=ON" -e
  "ENABLE_TOPP_TESTING=ON" -e
  openms/qt5
  ./tools/travis/docker-cibuild.sh

