sudo: required
language: cpp
dist: trusty

before_install:
- svn co https://github.com/OpenMS/dockerfiles/trunk/travis
- docker build -t openms/qt5 -f travis/Dockerfile-qt5-travis .

script:
- docker run openms/qt5 ./tools/travis/lnx-cibuild.sh

